### ISSUE TITLE
Always-on firewall prevent daemon launching after system reboot

### ISSUE THREAD

**Issue by sith-on-mars** [ivpn/desktop-app-daemon#5] opened 2021-04-02 08:10 UTC
# Bug report

## Describe your environment

* Device: _____  
* OS name and version: OpenSUSE Tumbleweed Gnome
* IVPN app version: daemon version: v2.12.16, client version: v3.2.3

I use the rpm version of the app. Whenever I enabled always-on firewall, the VPN app just said "error connecting to IVPN daemon" and it seems the VPN daemon couldn't launch at all. I also wasn't able to connect to the internet and the only way to let me use the internet is to delete both the demon and client, delete the profile and then reboot. This problem didn't happen when I used on-demand firewall.

I'm not sure if this is an OpenSUSE issue, a rpm package issue or general issue.

![Screenshot from 2021-03-28 20-15-30](https://user-images.githubusercontent.com/37974764/113396063-65f11380-938a-11eb-8e84-57e26ac8eedd.png)

**Comment by stenya** [comment] 2021-04-02 08:22
Hi @sith-on-mars,
Thanks for the report. 

I can confirm the issue.
This happens on some Linux distributions ( we already have been informed about the same problem on Fedora ).
I will let you know as soon as the issue will be fixed.
But for now, I can offer you to not enable Persistent Firewall functionality.

**Comment by stenya** [comment] 2021-04-12 09:40
@sith-on-mars The issue is fixed in v3.3.7.
Feel free to reopen the ticket if you still have problems with it.

**Closed as completed by stenya** 2021-04-12 09:40 UTC
